# Generated by Django 2.2.12 on 2020-04-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='availability',
            new_name='available',
        ),
    ]
