# Generated by Django 2.2.12 on 2020-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200427_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
