# Generated by Django 2.2.12 on 2020-05-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_price_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='available',
            new_name='is_available',
        ),
    ]
