# Generated by Django 2.2.12 on 2020-05-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200502_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
