# Generated by Django 2.2.12 on 2020-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200503_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
