# Generated by Django 2.2.12 on 2020-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='is_verified',
        ),
    ]
