# Generated by Django 2.2.12 on 2020-05-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200502_1644'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('email', 'product')},
        ),
    ]
