# Generated by Django 2.2.12 on 2020-05-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20200502_1918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set(),
        ),
    ]
