# Generated by Django 2.2.12 on 2020-05-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20200502_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
