# Generated by Django 2.2.12 on 2020-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='verify',
            field=models.BooleanField(default=True),
        ),
    ]
