# Generated by Django 2.2.12 on 2020-05-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20200502_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='alert',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
