# Generated by Django 2.2.12 on 2020-05-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20200502_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', related_query_name='alert', to='products.Product'),
        ),
    ]
