# Generated by Django 2.2.12 on 2020-05-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20200503_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
