# Generated by Django 2.2.12 on 2020-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20200504_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_notified',
            field=models.DateTimeField(null=True),
        ),
    ]
