# Generated by Django 2.2.12 on 2020-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alert_last_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='verify',
        ),
    ]
