# Generated by Django 2.2.12 on 2020-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_remove_alert_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_frequency',
            field=models.PositiveIntegerField(choices=[(604800, 'Weekly'), (86400, 'Daily'), (43200, '2 per day'), (28800, '3 per day'), (0, 'All updates')], default=86400),
        ),
    ]
