# Generated by Django 2.2.12 on 2020-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200420_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
