# Generated by Django 2.2.12 on 2020-05-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_total_alerts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-total_alerts']},
        ),
    ]
